iekf_localizer_node:
  ros__parameters:
    # Frequency of the IEKF publisher in Hz. Default is 40 Hz
    freq: 40.0
    # Initial state and state covariance
    init:
      rpy: [0.0, 0.0, 0.0]
      vxyz: [5.5, 0.0, 0.0]
      xyz: [0.0, 0.0, 0.0]
      P: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01, 0.0,
          0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.01]
    # control noise standard deviation
    u_sigmas: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.0, 0.0, 0.0] # standard deviation
    # gravity. The default is (0.0, 0.0, -9.80665) for (x, y, z)
    g: [0.0, 0.0, -9.80665]
